name: Build and Publish NuGet Packages

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          6.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '6.x'

    - name: Determine version
      id: get_version
      shell: pwsh
      run: |
        $baseVersion = Get-Content -Path build.ps1 | Select-String -Pattern '\$baseVersion\s*=\s*"([^"]+)"' | ForEach-Object { $_.Matches.Groups[1].Value }
        $tagName = "${{ github.ref }}"
        
        if ($tagName -match 'refs/tags/v(.+)') {
          $baseVersion = $matches[1]
        }
        
        echo "BASE_VERSION=$baseVersion" >> $env:GITHUB_ENV

    - name: Build NuGet packages
      shell: pwsh
      run: |
        if ("${{ github.ref }}" -match 'refs/tags/v') {
          $buildScript = Get-Content -Path build.ps1 -Raw
          $buildScript = $buildScript -replace '(\$baseVersion\s*=\s*")[^"]+(")','$1${{ env.BASE_VERSION }}$2'
          Set-Content -Path build.ps1 -Value $buildScript
        }
        
        ./build.ps1

    - name: Setup GitHub Packages
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      shell: pwsh
      run: |
        foreach ($nupkg in Get-ChildItem -Path ./nupkg/*.nupkg) {
          dotnet nuget push $nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
        }

    - name: Publish to NuGet.org
      shell: pwsh
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        foreach ($nupkg in Get-ChildItem -Path ./nupkg/*.nupkg) {
          dotnet nuget push $nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./nupkg/*.nupkg
        name: RevitMCPSDK ${{ env.BASE_VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}